pkg/controller/submariner/submariner_controller.go

We allow the Submariner CR to omit certain values (currently, the
repository and version used for the container images), but we never
set the default values. This calls setSubmarinerDefaults() to ensure
the values are populated.

Ensure we set the default values

---

Dockerfile.dapper

Version 0.11.0 fixes the issues we had previously. This greatly speeds
up the build.

Install binary Operator SDK

---

Dockerfile.dapper

We use the fedora dapper image from submariner, and we remove the installation
of mercurial which does not seem to be necessary anymore.

Use the base dapper image from submariner

---

scripts/kind-e2e/e2e.sh

This will run a cluster-info dump on each cluster in case of
failure during the deployment, or basic check phase.
The cluster dump contains information about all pods, deployments,
services, etc, along with the pod logs for each cluster.
Tested on: https://api.travis-ci.com/v3/job/250733047/log.txt

Dump clusters information on error

---

pkg/subctl/datafile/datafile.go
pkg/subctl/datafile/datafile_test.go

This commit defines the data exported from the broker creation
and imported on cluster join. It contains the submariner k8s broker
URL, the token for connection, and the IPSec PSK as a k8s secret.

Datafile handling pkg

---

go.mod
pkg/broker/broker_test_suite.go
pkg/broker/ipsec_psk.go
pkg/broker/ipsec_psk_test.go
pkg/broker/secret.go
pkg/subctl/cmd/createbroker.go

The purpose of this, is that we will be providing an unified IPSEC key between runs of
subctl, aditionally this could be used to automate rotation of IPSEC keys.

Generate random Broker PSK and store in Secret

---

pkg/subctl/operator/install/crds/crds_test.go
pkg/subctl/operator/install/crds/ensure.go

The unit tests have been extended to cover the case where
updateOrCreateCRD was called when the CRD already existed.

Fix error handling in updateOrCreateCRD

---

pkg/subctl/cmd/info.go
pkg/subctl/cmd/root.go

Errors should always be returned last.

Fix getClients() return order

---

pkg/discovery/network/network.go
pkg/subctl/cmd/deploybroker.go
pkg/subctl/cmd/join.go
pkg/subctl/cmd/root.go
scripts/kind-e2e/e2e.sh

This commit adds the network discovery logic, and also reuses the
join logic on the deploy-cluster side.
The priority of the CIDRs will be:
1) command line overriden CIDRs, with a warning if they don't match discovery
2) discovered network details
3) ask admin

Integrate network discovery into the join command

---

pkg/subctl/cmd/join.go
pkg/subctl/operator/deploy/ensure.go
scripts/kind-e2e/e2e.sh
scripts/kind-e2e/lib_operator_verify_subm.sh

The current release of the operator doesn’t fill in default values, so
we need to ensure subctl does it instead.
ClusterID needs to be a valid DNS-1123 name, enforce that in Ensure()
for now.

Provide defaults, check clusterID

---

pkg/subctl/cmd/root.go

Handling the comments by @dfarrell07 about retry times on previous commits. This should make it work more safely.

Handle the retries of node-labeling with exponential backoff

---

pkg/subctl/cmd/info.go
pkg/subctl/operator/install/ensure.go
pkg/subctl/operator/install/scc/ensure.go
pkg/subctl/operator/install/serviceaccount/ensure.go

When installing on top of OpenShift the operator service
account must be added to the privileged scc, otherwise it
won't be able to create privileged pods.

Handle OpenShift's privileged SCC

---

pkg/discovery/network/canal.go
pkg/discovery/network/canal_test.go
pkg/discovery/network/network.go
pkg/discovery/network/openshift4.go
pkg/subctl/cmd/join.go

Crash on join happened if networkDiscovery was nil, which can
still happen even for err == nil.

Discovery for canal-flannel, and avoid crash on join

---

pkg/controller/submariner/submariner_controller.go
pkg/subctl/cmd/join.go

This avoids having to explain what it’s used for...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/submariner-io/submariner-operator/55)

Add a default colour code

---

pkg/subctl/cmd/join.go
pkg/subctl/operator/deploy/ensure.go

This reduces the number of arguments to deploy.Ensure().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/submariner-io/submariner-operator/57)

Pass a filled-in SubmarinerSpec

---

pkg/subctl/cmd/root.go

This enables compilation of the required auth plugins used
in google cloud.
Fixes Issue: #67
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/submariner-io/submariner-operator/68)

Fixes subctl compatibility issue with GKE kubeconfig files

---

pkg/subctl/cmd/deploybroker.go
scripts/kind-e2e/e2e.sh

This changes the broker deployment command so that it doesn’t join the
cluster by default, and adds a --dataplane option to join (instead of
the --no-dataplane option to disable joining).
This is an alternative to #70, and would also fix: #69.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/submariner-io/submariner-operator/75)

Flip the dataplane default

---

pkg/subctl/cmd/deploybroker.go

To simplify documentation, and because it’s used in demos, we should
keep --no-dataplane for now. This patch allows it, sets it by default,
but effectively ignores it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/submariner-io/submariner-operator/87)

Allow --no-dataplane

---

pkg/subctl/operator/install/ensure.go

When deploying the operator without a pre-loaded container image, the
operator can spend quite a while in the ContainerCreating phase, with
no feedback on screen. This adds a “Deploying the operator...”
message, which is replaced once the operation completes (successfully
or otherwise).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/submariner-io/submariner-operator/83)

Tell the user the operator is being deployed

---

pkg/subctl/cmd/deploybroker.go
pkg/subctl/cmd/join.go
pkg/subctl/cmd/root.go

This replaces most panicOnError calls with exitOnError calls with
appropriate error messages. This avoids confusing stack traces.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/submariner-io/submariner-operator/94)

Provide friendlier error messages on exit

---

pkg/subctl/cmd/root.go

When attempting to label a gateway, if subctl doesn’t find any
non-master nodes, it errors out with an obscure error message (“please
provide options to select from”, produced by the survey library).
This patch handles this situation explicitly, with a friendlier error
message (“there are no non-master nodes in the cluster”).

Provide explicit error if no non-master nodes

---

pkg/subctl/cmd/join.go
pkg/subctl/cmd/root.go

In subctl, if we don’t find any candidate nodes for labeling, skip
instead of exiting. This sets up Submariner, which will then wait for
a gateway to be labeled.
This also adds a --no-label option to skip labeling in all cases.

Skip labeling if there are no nodes

---

scripts/kind-e2e/e2e.sh

Cluster dump only generates a lot of noise on the logs, and nothing
useful so far. We're removing it because it's caused more headaches
than help.

Remove cluster-dump on error

---

pkg/subctl/cmd/deploybroker.go
pkg/subctl/datafile/datafile.go
pkg/subctl/lighthouse/deploy/ensure.go

1. Adds 'service-discovery' option to subctl when deploying broker
2. Adds the parameter to subm file so can be used when joining clusters

Add lighthouse option to subctl

---

pkg/broker/ensure.go
pkg/subctl/cmd/deploybroker.go
pkg/subctl/datafile/backup.go
pkg/subctl/datafile/datafile.go
pkg/subctl/datafile/datafile_test.go
pkg/subctl/datafile/ipsec_psk.go
pkg/subctl/datafile/ipsec_psk_test.go

Subctl should not store the IPSEC secret in the broker, because
even if the broker is compromised, still without the IPSEC factor
an attacking actor could not connect to the remote clusters.
To minimize the risk of IPSEC key loss the broker-info.subm file
is backed up, and if the file is found locally, it's IPSEC PSK key
is reused. Also can be provided via a cmdline flag "--ipsec-psk-from"
Fixes: #93

Remove IPSEC secret storage in broker

---

pkg/subctl/cmd/root.go
pkg/subctl/cmd/version.go

Sometimes we have crash reports, but no info on which version was it ran from.
This will dump the version of subctl as part of the exit or panic error.

Version on crash

---

scripts/kind-e2e/e2e.sh

Also remove some duplication around subctl usage in the e2e.sh script.
Fixes: #116

Force subctl output through a pipe to avoid spinner in logs

---

Makefile

Currently, we rebuild the embedded YAMLs if the source YAMLs change;
but since the list of YAMLs is contained in yamls2go, we need to watch
that too.

Ensure embedded YAMLs are generated if yamls2go changes

---

pkg/subctl/operator/common/embeddedyamls/generators/yamls2go.go

Explain the backtick handling in embedded YAML

---

pkg/subctl/lighthouse/deploy/ensure.go
pkg/subctl/operator/kubefed/ensure.go
pkg/subctl/operator/kubefedcr/ensure.go

I wasn’t able to generate the correct KubeFed clientset, so this runs
kubectl to deploy the CR.

Deploy the KubeFed controller

---

pkg/subctl/cmd/join.go
pkg/subctl/lighthouse/deploy/ensure.go
pkg/subctl/lighthouse/dns/ensure.go
pkg/subctl/lighthouse/install/ensure.go

This pulls in the Lighthouse DNS setup inside the general Lighthouse
setup, so that external callers don’t need to know about it. It also
centralises version handling for the Lighthouse components.

Encapsulate Lighthouse DNS handling

---

pkg/subctl/cmd/deploybroker.go
pkg/subctl/cmd/info.go
pkg/subctl/cmd/join.go
pkg/subctl/cmd/root.go
scripts/kind-e2e/e2e.sh

... as well as the kubeconfig file. This will be necessary for KIND
upgrades since KIND (and Kubernetes in general) is moving away from
separate kubeconfig files.

Support specifying contexts

---

deploy/operator.yaml
pkg/controller/submariner/submariner_controller.go
pkg/controller/submariner/submariner_controller_test.go
pkg/subctl/cmd/join.go
pkg/subctl/cmd/root.go
pkg/subctl/lighthouse/deploy/ensure.go
pkg/versions/versions.go

This will fail until we release 0.1.0 in submariner.

Bump versions to 0.1.0 and centralize versions

---

Makefile

vendor/modules.txt is updated whenever "go mod vendor" is run, so we
can use that to track vendor freshness compared to go.mod. This avoids
problems with an already-present but out-dated vendor directory when
we add or update dependencies.

Vendor as needed

---

pkg/subctl/lighthouse/dns/ensure.go

For OpenShift we need a different CoreDNS image, this ensures that we
actually use it.

On OpenShift, use the appropriate CoreDNS image

---

pkg/subctl/cmd/join.go

When kubefed join step of subctl join fails, it only shows a numeric
error code and not actual error output. This change is to show the
actual error output to make troubleshooting easier.

subctl: add more information to join error

---

pkg/subctl/cmd/deploybroker.go
pkg/subctl/cmd/join.go
pkg/subctl/lighthouse/deploy/ensure.go
pkg/subctl/lighthouse/install/crds/ensure.go
pkg/subctl/lighthouse/install/ensure.go
pkg/subctl/operator/kubefed/ensure.go
pkg/subctl/operator/kubefedcr/ensure.go

Currently, subctl runs kubectl and kubefedctl in the default context:
whichever kubeconfig is the default, and whichever context is the
default. If the user specifies --kubeconfig and/or --kubecontext on
the subctl command-line, this causes mix-ups since subctl and the
other tools don’t touch the same cluster.
With this patch, kubectl and kubefedctl are given the appropriate
flags as necessary. This isn’t particularly elegant but it will all be
removed once KubeFed is removed.
Fixes: #180

Provide config and context arguments to commands

---

pkg/discovery/globalnet/globalnet.go
pkg/discovery/globalnet/globalnet_suite_test.go
pkg/discovery/globalnet/globalnet_test.go
pkg/subctl/cmd/join.go
pkg/subctl/datafile/datafile.go

When joining a new cluster, check if serviceCIDR
or clusterCIDR overlaps with any existing cluster.
This code will also be reused for
Globalnet (overlapping cidrs).

subctl: Check for overlapping CIDRs

---

pkg/subctl/cmd/join.go

Need to check for nd != nil.
See https://github.com/submariner-io/submariner/issues/367 for details.

Fix panic in getPodCIDR

---

pkg/discovery/network/network.go

Currently when we query the cluster info using "subctl info ..." command
the output displays ClusterIP Cidrs and Pod CIDRs. In K8s, POD CIDR is
usually referred to as Cluster CIDR. So, using ClusterIP CIDR for Service
CIDR is really confusing. This patch modifies the output accordingly.
Signed-off-by: Sridhar Gaddam <sgaddam@redhat.com>

Rename ClusterIP CIDRs to Service CIDRs

---

pkg/subctl/cmd/root.go

The previous message "No available node, skipping labeling" was
clarified to indicate that no worker node was found.

Clarify message when no node found to label

---

pkg/subctl/lighthouse/deploy/ensure.go

The Lighthouse deployment was missing a check on the
--service-discovery flag; this adds it.

Only enable service discovery if requested

---

pkg/subctl/cmd/join.go

When subctl join is run against an OpenShift cluster with a deployed
cluster version operator, and service discovery is enabled, we now ask
for confirmation before continuing, because installing service
discovery will disable the CVO.
Fixes: #167

Ask for confirmation before disabling OpenShift CVO

---

pkg/subctl/lighthouse/deploy/ensure.go

The broker doesn’t need DNS overrides (and we don’t want to replace
its CoreDNS and break its CVO, or ask the user about it).
(cherry picked from commit f527a314985d5a13fc53951775f4be646091e98d)

Don’t set DNS up on broker

---

go.mod
pkg/controller/submariner/submariner_controller.go
pkg/controller/submariner/submariner_controller_test.go

When the operator Submariner instance changes, update the gateway and
route-agent DaemonSets.

Implement DaemonSet update in ReconcileSubmariner

---

README.md

Added info about using merged-kubeconfig for joining the cluster.

---

pkg/versions/versions.go

* submariner to v0.1.1
* submariner-operator to v0.1.1
* lighthouse needs no update since there are no code changes between since v0.1.0,
all changes have been around CI and docs.
(cherry picked from commit fb1fea63edcd93e456e0dde2e7832ca6ac041fc8)

Update versions to latest tags

---

pkg/broker/rbac.go
pkg/subctl/datafile/datafile_test.go

Sometimes the service account inverts the order of the secrets,
and our code is not smart enough, this patch fixes it looking
for the right secret.
Fixes: #244

Fix issue with wrong token stored in subm file (OpenShift)

---

Makefile

Targets can have multiple sets of dependencies, so we can specify
build-subctl’s dependencies, and specify that bin/subctl depends on
that.
(This can’t be extended too far, otherwise we end up with too many
phony dependencies in the chain, and everything gets rebuilt all the
time.)
Fixes: #126

Describe subctl dependencies on build-subctl

---

Dockerfile.dapper

... to avoid the bump to kind 0.6.1 for now.

Use dapper-base e791638

---

pkg/subctl/lighthouse/deploy/ensure.go
pkg/subctl/lighthouse/install/crds/ensure.go
pkg/subctl/lighthouse/install/ensure.go
pkg/subctl/operator/kubefed/ensure.go

When enabling namespaces in kubefed, use kubeContext if available.

Use context when enabling namespaces

---

scripts/kind-e2e/e2e.sh

This PR also updates the max_attempts to 30 (secs), which is
the time we wait for a service to get annotated with globalip.
Signed-off-by: Sridhar Gaddam <sgaddam@redhat.com>

Specify context while retrieving globalip

---

pkg/subctl/cmd/deploybroker.go

Issue-258
When user specifys a global cluster size that is not power of 2,
we upscale it to nearest power of two that can accommodate user size.
If this size is bigger than what Global CIDR can allow, we return
an error to user with a recommended size.
This error displays the "upscaled" value instead of what was
passed by user, which can be confusing. This patch is to display
the value passed by user.

Return appropriate err for globalClusterSize

---

pkg/subctl/lighthouse/dns/ensure.go
pkg/subctl/lighthouse/install/deployment/ensure.go
pkg/subctl/operator/common/operatorpod/ensure.go
pkg/subctl/operator/kubefed/ensure.go

kubefed deployment is timing out in CI. Increase timeout duration
so we wait longer for it to come up. Errors are also bit misleading
as they don't truly show which step of kubefed failed. Modify the
error messages to accurately specify which step failed.

Improved retry and errors for kubefed deployment

---

scripts/kind-e2e/e2e.sh

Based on the current design of LightHouse (that supports Cross Cluster Service Discovery), there is a small possibility where the initial DNS resolution for a remoteService might get resolved to ClusterIP first and subsequently get updated to globalIP (that is annotated on the remote service). 
In the current e2e validation, we are initially checking curl to nginx-demo and later validating if the resolvedIPAddress matches to remoteServiceGlobalIP. But when curl to nginx-demo fails, its hard to know if the failure was due to resolution of wrongIP (aka ClusterIP) or if its some datapath issue. This PR moves the validation prior to datapath testing which makes it easier for us to understand the reason for failure.

Validate resolved-ip to globalIp before validating datapath

---

pkg/versions/versions.go

Lighthouse is maintained on rc0 as it did't undergo any change.

Update versions.go for new RC1

---

pkg/discovery/globalnet/globalnet.go
pkg/subctl/cmd/deploybroker.go
pkg/subctl/cmd/join.go
scripts/kind-e2e/e2e.sh
scripts/kind-e2e/lib_operator_verify_subm.sh

Currently --globalnet-cluster-size can be specified only during broker
installation. This adds option to give a different size during join.
Closes #268

Add globalnet-cluster-size option to join

---

deploy/cluster_role.yaml

As part of supporting connectivity from HostNetwork to remoteClusters, globalnet
controller annotates a node with globalIP. This PR adds the necessary roles for
globalnetController.
Fixes Issue: https://github.com/submariner-io/submariner-operator/issues/305
Signed-off-by: Sridhar Gaddam <sgaddam@redhat.com>

Operator: Add role for globalnet controller to annotate a node

---

build/Dockerfile

This shrinks the resulting image slightly, but more importantly,
reduces our security footprint (see
e.g. https://quay.io/repository/submariner/submariner-operator/manifest/sha256:174084b6fa69f2245a50284eddabf1d2e721a71993b133287ab4c7d254c8d673?tab=vulnerabilities
for one example). The published vulnerabilities so far don't affect
us, but it will simplify our users' experience if we avoid unnecessary
alerts.

Remove unnecessary packages from the operator image

---

deploy/crds/submariner.io_submariners_crd.yaml
pkg/apis/submariner/v1alpha1/submariner_types.go
pkg/apis/submariner/v1alpha1/zz_generated.openapi.go
pkg/controller/submariner/submariner_controller.go

This adds a standard status object returning parameters which the user
might want to check.

Add basic operator status

---

pkg/subctl/lighthouse/dns/ensure.go
pkg/subctl/lighthouse/install/crds/ensure.go
pkg/subctl/lighthouse/install/deployment/ensure.go
pkg/subctl/operator/common/deployments/utils.go
pkg/subctl/operator/common/operatorpod/ensure.go
pkg/subctl/operator/kubefedop/clusterrole/ensure.go
pkg/subctl/operator/kubefedop/clusterrolebinding/ensure.go
pkg/subctl/operator/kubefedop/crds/crds_test.go
pkg/subctl/operator/kubefedop/crds/ensure.go
pkg/subctl/operator/kubefedop/role/ensure.go
pkg/subctl/operator/kubefedop/rolebinding/ensure.go
pkg/subctl/operator/submarinercr/ensure.go
pkg/subctl/operator/submarinerop/crds/crds_test.go
pkg/subctl/operator/submarinerop/crds/ensure.go
pkg/subctl/operator/submarinerop/scc/ensure.go
pkg/subctl/operator/submarinerop/serviceaccount/ensure.go
pkg/utils/createorupdate.go
pkg/utils/createorupdate_test.go

All Kubernetes update operations should be retried on conflicts,
i.e. the object being changed has changed on the server since it was
retrieved.
Fixes: #255

Ensure that update operations are retried

---

README.md

Since we use Dapper, the build requires a working Docker setup.
Fixes: #319

Document the build prerequisites

---

pkg/apis/submariner/v1alpha1/submariner_types.go
pkg/apis/submariner/v1alpha1/zz_generated.deepcopy.go
pkg/controller/submariner/submariner_controller.go

This also drops the CableDriver entry since the cable driver in use is
reflected (accurately) in the Gateway information.

Include Gateway information in the operator status

---

pkg/subctl/cmd/deploybroker.go
pkg/subctl/lighthouse/deploy/ensure.go

Setup Service Discovery step of deploy-broker gives incorrect status
msg. We no longer deploy controller on broker, or do anything on broker
from subctl. Broker installation is handled by operator.

Remove unused code for deploy-broker

---

pkg/subctl/operator/submarinerop/crds/ensure.go

Whe the gateways are listed via
```
kubectl get Gateways -A
```
This detail of the object will be printed.

This commit adds the ha-status printable column to the gateway CRD

---

.travis.yml

After introducing additional travis jobs in PR #254 all of them try to
deploy, we should limit deployment to only one.

Fix travis release script

---

pkg/subctl/cmd/join.go

Enhance 'subctl join' to be able specify globalCIDR
for each cluster while joining. The logic implemented is
```
if globalcidr specified by user
error if it overlaps with other clusters
if globalcidr is preconfigured
take pre-configured value
else take specified value
if not specified by user
if globalcidr is preconfigured
take pre-configured value
else automatically assign value
```
It also checks if the specified CIDR is valid and that both globalcidr and globalnet cluster size are not specified.
Closes: #298
Signed-off-by: Janki Chhatbar

Specify globalCIDR while joining cluster

---

go.mod
go.sum
pkg/versions/versions.go

Lighthouse hasn't changed the go code.

Bump submariner and operator versions to 0.3.0-rc2

---

Makefile

Following it's removal on Shipyard [1] we need to send it properly in
the `--deploytool_submariner_args`.
[1](https://github.com/submariner-io/shipyard/pull/140)

Send cable_driver properly

---

.travis.yml
pkg/subctl/cmd/version.go
pkg/version/version.go
scripts/build-subctl

In subctl version, display the output of "git describe --tags" instead
of the full commit hash. On development versions, this will show the
closest tag, followed by the number of commits since the tag, and the
short hash of the current commit:
$ bin/subctl version
subctl version: dev
built from git ref: v0.3.0-rc2-2-g95d2c84
When subctl is built from a commit which is itself tagged (i.e. when
building a release), it will only show the tag:
$ bin/subctl version
subctl version: v0.3.0
built from git ref: v0.3.0
Fixes: #355

Use the closest git reference instead of the commit hash

---

pkg/subctl/cmd/deploybroker.go
pkg/subctl/datafile/datafile.go

While copying the output of `subctl deploy-broker -h` into the website
subctl docs, it was noted during review that this output's useage of
IPSEC over IPsec  was inconsitenat with the norms of the website. After
digging, it also became apparent the correct format is IPsec (from
Wikipedia and RFC 4301).

Rename IPSEC->IPsec in outputs

---

Makefile.dapper

Targets offered by the in-Dapper Makefile are hidden by files or
directories of the same name, for example “deploy”. This patch marks
all such files/directories, apart from those starting with “M” (to
avoid problems with the Makefiles themselves), as phony, with an
explicit build target.
This allows
make deploy
to work even though there’s a deploy directory.

Ensure that files/directories don’t hide Dapper targets

---

go.mod
go.sum
pkg/subctl/cmd/verify_connectivity.go

Otherwise the globalnet detection is not triggered and
verify-connectivy will not work when globalnet is enabled.
Fixes-Issue: #381
Depends-On: https://github.com/submariner-io/submariner/pull/566

Import the submariner e2e framework in verify-connectivity

---

deploy/lighthouse/cluster_role.yaml
deploy/lighthouse/crds/serviceexport_crd.yaml
pkg/broker/ensure.go
pkg/broker/rbac.go
pkg/lighthouse/crds.go
pkg/subctl/operator/common/embeddedyamls/generators/yamls2go.go
pkg/subctl/operator/lighthouse/crds/ensure.go
pkg/utils/createorupdate.go

Adds the ServiceExport CRD for lighthouse U/S alignment, only
on the clusters where the operator is installed, not the broker.
Related-Issue: https://github.com/submariner-io/lighthouse/issues/78

Add ServiceExport CRD

---

Makefile
scripts/kind-e2e/lib_operator_verify_subm.sh

This drops the failing e2e checks (which are no longer possible since we only ship the operator binary in the container), and deploys the newly-built container image.
Fixes: #398.

Test built container

---

scripts/kind-e2e/e2e.sh
scripts/kind-e2e/nginx-demo-export.yaml

Otherwise the dns query won't work because lighthouse
now requires a ServiceExport.
Fixes-Issue: https://github.com/submariner-io/shipyard/issues/182

Deploy the ServiceExport in the lighthouse case

---

Dockerfile.dapper
Makefile

The previous code would still use the one from quay (as it's not present
"inside" the KIND deployment), this should use the local one that was
built.
Resolves: #414

Use the actual local operator image in E2E

---

.github/workflows/subctl_bleeding_edge.yml

This GitHub Action should upload updated binaries to the "Bleeding edge"
release each time a new commit is merged to master.

Release binaries in "Bleeding edge" release

---

pkg/subctl/cmd/verify.go
scripts/kind-e2e/e2e.sh

Submariner E2E requires submariner namespace for some of its
validations. Currently `verify-connectivity` doesn't specify any value
for it which causes E2E to fail. This adds a new option
`submariner-namespace` to `verify-connectivity`
Fixes #420

Add submariner-namespace to verify-connectivity

---

.github/workflows/subctl_bin.yml
.github/workflows/subctl_bleeding_edge.yml
scripts/build-cross
scripts/build-subctl

Under specific conditions (OSX, some types of mounts..) upx unpacking
of the executable generates a segmentation fault.
A decission was made to move into a tar packaged file, this will
also allow us to include more files in the future if necessary.
Extracting the files can be performed as:
```bash
$ tar xvf bin/subctl-dev-linux-amd64.tar.xz
subctl-dev-linux-amd64/subctl-dev-linux-amd64
```
Fixes-Issue: #335

Stops packing subctl with upx and generates an tar.xz

---

deploy/cluster_role.yaml
deploy/cluster_role_binding.yaml
pkg/controller/helpers/helpers.go
pkg/controller/servicediscovery/servicediscovery_controller.go
pkg/subctl/lighthouse/dns/ensure.go
pkg/subctl/operator/common/embeddedyamls/generators/yamls2go.go
pkg/subctl/operator/submarinerop/serviceaccount/ensure.go
scripts/preload_images

Lighthouse plugin now runs in a stand-alone DNS server.
The domain name supercluster.local needs to be used to resolve service
running in other clusters.
The in cluster-dns server will use forward plugin to send a request to
supercluster.local to lighthouse DNS Server.
The e2e is updated to resolve supercluster.local domain name.
Fixes Issue: #345

Implement Lighthouse using stand-alone DNS Server

---

pkg/subctl/cmd/verify.go
scripts/kind-e2e/e2e.sh

The gateway-failover (redundancy) tests are added.
The new format is:
```
subctl verify k1 k2 [--enable-disruptive] [--only service-discovery,network-policy,...]
```
subctl will prompt for disruptive tests if --enable-disruptive is not enabled and any
disruptive test is expected to be executed, so the user is warned before execution
and excluded if the user does not want to perform those verifications.

Update the verify command behaviour

---

pkg/controller/servicediscovery/servicediscovery_controller.go
pkg/subctl/operator/lighthouse/ensure.go
pkg/subctl/operator/lighthouse/scc/ensure.go

The submariner-lighthouse service account is added in
privileged scc. An issue with cluster-dns-operator update is
fixed.

Fix issues in Openshift deployment

---

pkg/versions/versions.go

This preparates subctl/operator for 0.4.0-rc1 release.

Bump component versions to 0.4.0-rc1

---

pkg/controller/submariner/submariner_controller.go

... so that the engine container can use the host iptables.

Mount the host file system in the engine

---

.github/workflows/e2e.yaml
Makefile

Instead of passing with ARGS flags, it's possible to run e.g. `make e2e
using=lighthouse` to deploy with service discovery.

Support make flag `using=` to pass options

---

scripts/subctl/getsubctl.sh

This script can be published on the website to let users download
and install subctl on specific versions.
The script supports binary upx releases as well as tar.xz packed files
as #418 proposes.
Related-To: #418

Add a script to download and install subctl

---

pkg/controller/submariner/submariner_controller.go
scripts/kind-e2e/lib_operator_verify_subm.sh

In K8s the default termination grace period for a Pod is 30
secs. However, for Submariner Pods, we were configuring this as
0 secs, because of which, cleanup was not happening in a
consistent manner and we are seeing failures in CI jobs.
This PR modifies the terminationGracePeriodSeconds to 10 secs.
Along with this change, for the Globalnet Pod, it also uses the proper
namespace of submariner in the excluded namespaces.
Fixes issue: https://github.com/submariner-io/submariner-operator/issues/444
Signed-off-by: Sridhar Gaddam <sgaddam@redhat.com>

Fix terminationGracePeriodSeconds in Submariner Pods

---

pkg/subctl/cmd/deploybroker.go

As discussed recently in the slack channel, it's not working properly
and makes the list of flags for deploy-broker more complicated to
understand. This simplifies the picture.
Depends-On: https://github.com/submariner-io/shipyard/pull/205

Remove the --dataplane flag for deploy-broker

---

pkg/subctl/cmd/deploybroker.go
pkg/subctl/lighthouse/deploy/ensure.go

Those flags were not used anymore, and we use the general repository
and version parameters.
This commit also moves the Flag logic for --service-discovery back
into deploy broker as we do for all flags.

Remove --service-discovery-repo and --service-discovery-version

---

pkg/discovery/globalnet/globalnet.go
pkg/subctl/cmd/join.go
pkg/subctl/datafile/datafile.go

The ca.crt stored in the broker information file reflects the trust
chain of the token, not necessarily the trust chain of the API
endpoint; but we're using it for the latter.
This breaks setups where the API endpoint is rooted in a
publicly-available CA.
(This is a test to see what happens in non-public setups...)
Fixes: #451

Check whether the CA trust chain is needed

---

scripts/build-cross

As pointed out by Mike Kolesnik, we probably don’t have any 32-bit
users.
Since we’re “freeing up” some build capacity, let’s add arm64.

Drop 32-bit arches, add arm64

---

pkg/subctl/cmd/verify.go

We check for io.EOF returned from survey.AskOne to determine if
run with no stdin in order to print the non-interactive usage message
wrt enable-disruptive. However this only works if stdin is redirected
from /dev/null, ie "subctl ... < /dev/null". But if stdin is closed via
"subctl ... <&-", then it returns an os.PathError indicating
"bad file descriptor". We should check for this as well.

Fix non-interactive check in subclt verify

---

go.mod

Since this file gets updated in CI, the version is calculated as `dev`
instead of the real tag.

Fix the release versioning

---

deploy/crds/submariner.io_submariners_crd.yaml
pkg/apis/submariner/v1alpha1/zz_generated.openapi.go

The Submariner status cableDriver member was removed in 75e93516fb1e
but the operator wasn’t re-generated. This fixes that.

Remove left-over cable driver status handling

---

pkg/subctl/cmd/version.go
pkg/version/version.go
scripts/build-subctl

Commit 60745085fa34 ("Use `git describe` to get a coherent version")
includes the commit information (if relevant) in VERSION, so subctl no
longer needs a separate git ref.

Drop GitRef, its info is present in VERSION

---

pkg/discovery/network/network.go

networkPluginsDiscovery can return nil, which leads to a SIGSEGV when
we try to set GlobalCIDR in the returned object. Only update discovery
after checking its non-nil.

Network discovery: only access discovery if non-nil

---

pkg/apis/submariner/v1alpha1/submariner_types.go
pkg/apis/submariner/v1alpha1/zz_generated.deepcopy.go
pkg/controller/submariner/submariner_controller.go

Currently the Gateway types aren’t registered; this fixes that. It
turns out we also need to fill in the GatewayList meta-data if we want
to add it as-is to the status, so this also changes the status to
include the Gateway slice instead.

Allow the operator to retrieve Gateway objects

---

pkg/subctl/cmd/verify.go

When disruptive verifications are requested, subctl prompts the user
to confirm their intention, but then assumes an error occurred. This
patch fixes that, so that the user’s answer to the prompt is actually
taken into account.

Fix the disruptive verification prompt

---

Makefile

Now that we no longer have any build scripts in scripts, we no longer
need to load them as Make targets.

Drop $(TARGETS)

---

pkg/subctl/cmd/verify.go
scripts/kind-e2e/e2e.sh

Currently, the e2e connection-attempts is set to 2 and this
can cause failures in GN jobs. This PR modifies connection-attempts
to 4 while decreasing the connection-timeout to 20 secs.

Increase e2e connection timeout

---

pkg/controller/submariner/submariner_controller.go
scripts/kind-e2e/lib_operator_verify_subm.sh

In one of the earlier PRs, we modified the terminationGracePeriodSeconds
to 10 secs. However, its seen that this is causing more CI failures
during e2e redundancy tests. Ideally, once the Pods are terminated,
it should cleanup itself ASAP but it is seen that SM Pods are sometimes
taking time to exit and during this Period since there is no active SM
Pod running, this is triggering some failures.
Until we figure out the exact reason why the Pods are taking time for
cleanup, this PR resets the terminationGracePeriodSeconds.
Related to: https://github.com/submariner-io/submariner-operator/issues/444
Related to: https://github.com/submariner-io/submariner-operator/pull/445

Reset terminationGracePeriodSeconds for SM Engine and RouteAgent Pods

---

Makefile

It's needed by the import_image function
Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

Load versions for preload images

---

Makefile

We can't fully validate the codebase if the embedded YAMLs aren't
generated.

Ensure embedded YAMLs are generated for validation

---

deploy/lighthouse/crds/serviceimport_crd.yaml
pkg/lighthouse/crds.go
pkg/subctl/operator/common/embeddedyamls/generators/yamls2go.go

ServiceImport CRD will be installed during deploy broker and join.

Add ServiceImport CRD

---

pkg/subctl/cmd/join.go

Since https://github.com/submariner-io/submariner-operator/pull/542 default
repository handling is not done for submariner operator. This
moves the default repository as the parameter default and makes
sure that populateSubmarinerSpec will not tamper any global variable.

Fix image handling for operator

---

go.mod
pkg/controller/submariner/submariner_controller.go
pkg/controller/submariner/submariner_metrics.go

This is mostly about the framework (which, it turns out, is very
simple), but includes two metrics:
* a counter of the number of reconciliations
* a gauge tracking the number of gateways
These are exposed on the operator, on port 8383, /metrics.

Add basic metrics

---

pkg/utils/createorupdate.go

If Update returns errors.IsConflict, it needs to be retried. Don't
modify error returned by Update so RetryOnconflict logic can handle it
correctly. Any other errors will be logged/caught by callers.

Don't modify error on Update

---

pkg/apis/submariner/v1alpha1/submariner_types.go
pkg/controller/submariner/submariner_controller.go
pkg/controller/submariner/submariner_controller_test.go
pkg/controller/submariner/submariner_networkdiscovery.go
pkg/discovery/globalnet/globalnet.go
pkg/discovery/network/network.go
pkg/subctl/cmd/join.go
scripts/kind-e2e/lib_operator_verify_subm.sh

This pull requests moves the network discovery to the operator.
This allows for configuring the operator with empty cluster and service CIDRs.
Subctl will still try to discover the details to make sure that the operator will be able
to figure out those details, and if it is not possible, it will prompt the user and write
those values in the operator CR.

Move network discovery to the operator

---

pkg/broker/ensure.go

In PR[1], submariner broker admin role is updated to include configMaps.
However, if users try to the newer subctl on an existing deployment, the
roles are not updated on the broker. This PR fixes it.
[1] https://github.com/submariner-io/submariner-operator/pull/501
Related to: https://github.com/submariner-io/submariner-operator/issues/504

Update submariner-k8s-broker-admin role if already present

---

pkg/controller/submariner/submariner_controller.go
pkg/controller/submariner/submariner_metrics.go

Operators already count reconciliations, with more information than we
provide, so there’s no point in having our own reconciliation metric.

Operators track reconciliations, no need to do it

---

pkg/discovery/globalnet/globalnet.go
pkg/subctl/cmd/join.go

As part of some recent changes, there is a regression
because of which an empty "global_cidr" is stored in
the submariner-globalnet-info configMap on Broker.
This PR fixes this issue and also the associated
segmentation fault which was the side-effect.
Fixes issue: https://github.com/submariner-io/submariner-operator/issues/561

Fix empty globalCidr in submariner-globalnet-info ConfigMap

---

deploy/cluster_role.yaml
deploy/cluster_role_binding.yaml

Discovery of the network looks at ClusterNetwork, and if that
fails it will look for specific configurations and generic
heuristics.
Fixes-Issue: #557

Fix the operator cluster permissions for discovery

---

pkg/controller/servicediscovery/servicediscovery_controller.go

PR #488 added Globalnet_Enabled flag to spec but missed setting it in env
variable for the Lighthouse agent PODs. So the flag is never available
to agent code running in the pod. This adds the env variable to POD spec
based on flag value in the Submariner spec.

Set Globalnet_enabled flag in lighthouse agent env

---

pkg/lighthouse/crds.go

Due to incorrect variable name service import installation
was skipped.

Fix the service import installation

---

.golangci.yml
pkg/apis/submariner/v1alpha1/servicediscovery_types.go
pkg/apis/submariner/v1alpha1/submariner_types.go
pkg/discovery/globalnet/globalnet.go
pkg/internal/cli/logger.go

While re-ordering structs, also put their fields in alphabetical order
within memory-order constraints.

Enable maligned memory use linter, fix errors

---

pkg/subctl/cmd/show.go

Currently the help displays info specific to the networks sub-command.
Now it displays general info not specific to any sub-command.

Modify subctl show command help

---

deploy/lighthouse/cluster_role.yaml

Adds following permissions to lighthouse clusterrole
for `gateways.submariner.io`
- get
- list
- watch
This allows lighthouse to track changes to gateway status and know which
clusters are connected.
Fixes https://github.com/submariner-io/lighthouse/issues/113

Allow lighthouse access to gateways.submariner.io

---

pkg/controller/submariner/submariner_controller.go

Currently, the updateStrategy for Route-agent pods is set to RollingUpdate
with maxUnavailable as 1. Because of this, when the route-agent DaemonSet
is updated, the Pods are updated one after the other. While the rolling
update strategy is good for user-facing services, for route-agent DaemonSet
its not the most suitable one as it takes time for all the route-agent pods
to be updated in a large cluster.
Ideally, it would have been great if "Recreate" updateStrategy was supported
for DaemonSets, but unfortunately K8s does not support it. But an alternate
way to achieve something similar is to configure rollingUpdate.maxUnavailable
to 100% so that the DaemonSet controller can update all the route-agent Pods
in a single go.
https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/#dae …

Modify updateStrategy for Route-agent Pods

---

scripts/kind-e2e/lib_operator_verify_subm.sh

Seems this field was deprecated in the API [1] and it's causing K8s 1.16+
to fail because it's not there anymore, so just removing this check.
[1] https://v1-14.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#customresourcedefinitionspec-v1beta1-apiextensions-k8s-io
Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

Don't check CRD spec version

---

pkg/subctl/operator/submarinerop/serviceaccount/ensure.go

When upgrading a cluster, if the first operator ClusterRole we look at
doesn’t need updating, we stop there and skip the other operator
ClusterRole. This patch changes the behaviour so that both
ClusterRoles are checked.
(Ultimately we should clean up our ClusterRoles, but this will fix an
issue seen in production in the short term.)
Fixes: #609

Ensure all ClusterRoles are updated on upgrade

---

pkg/subctl/cmd/root.go

client-go knows how to deal with multiple kubeconfigs in a KUBECONFIG,
but we lose that by doing our own default handling. Using client-go
ensures that we get any fixes there, and provides cross-platform
default path handling as well as coping with multiple kubeconfigs.
This doesn’t quite fix #384, since the intention of the client-go
handling is context-based: it will look in all the kubeconfigs to find
the requested (or default) context, it won’t allow iterating over all
the kubeconfigs to access multiple clusters.

Rely on the default KUBECONFIG handling

---

pkg/controller/submariner/submariner_controller.go
pkg/controller/submariner/submariner_controller_test.go

During the initial releases of Submariner, submariner-gateway used to
be a Deployment. However, it was changed to a DaemonSet long ago and
many releases happened after that change. So we can remove the check
for deployment.
Related to: https://github.com/submariner-io/submariner-operator/issues/516

Avoid checking for EngineDeployment during reconcileEngineDaemonSet

---

pkg/subctl/cmd/join.go

Hopefully this, along with the improved help text, will make it
clearer that the option enables debugging in the pods, not debugging
in subctl.
Fixes: #545

Rename --subm-debug to --enable-pod-debugging

---

pkg/subctl/cmd/join.go

For endpoint slices we need 1.17, enforce that before deploying.
Fixes: #601

Check the K8s version on the cluster

---

pkg/subctl/cmd/deploybroker.go

This patch enables service discovery on deployments by default,
now that we implement the upstream API and we have a stable implementation
it's a good time to make this feature enabled by default.

Enable ServiceDiscovery by default on subctl

---

Makefile

The generators need to have all the dependencies, so ensure they're
available by vendoring first if necessary.

Vendor before calling operator-sdk generate

---

pkg/subctl/cmd/verify.go

Instead of hard-coding cluster names, pick up the names from the
client configuration, in the same way as join.
Fixes: #680

Use clusternames from client config in verify

---

pkg/controller/submariner/submariner_controller.go

When we try to create or update the Service Discovery CR, we end up
trying to create it twice, which results in
"error reconciling the Service Discovery CR: resourceVersion should
not be set on objects to be created"
in the logs.

Avoid double creation attempts for the SD CR

---

deploy/cluster_role.yaml
pkg/discovery/network/openshift4.go
pkg/discovery/network/openshift4_test.go

Networks in config.openshift.io/v1 is exposed for both
OpenShiftSDN and OVNKubernetes, while ClusterNetworks
seems to be only used with the operator for OpenShift SDN.
```
[majopela@bluehat subm-demo]$ subctl join --kubeconfig cluster-a/auth/kubeconfig broker-info.subm --cable-driver libreswan
* broker-info.subm says broker is at: https://api.majopela-cluster-a-09-10-20-1599722826.devcluster.openshift.com:6443
...
⠈⠑ Discovering network details     Discovered network details:
Network plugin:  OVNKubernetes
Service CIDRs:   [172.30.0.0/16]
Cluster CIDRs:   [10.128.0.0/14]
...
[majopela@bluehat subm-demo]$ subctl join --kubeconfig cluster-b/auth/kubeconfig broker-info.subm --cable-driver libreswan
* broker-info.subm says broker is at: …
```

Support detecting all networks in OpenShift

---

pkg/controller/submariner/submariner_controller.go
pkg/subctl/cmd/deploybroker.go
pkg/subctl/cmd/join.go
pkg/subctl/datafile/datafile.go

1. Adds `custom-domains` flag in `subctl`
2. Configure custom-domains parameter in submariner and
service-discovery specs.
Fixes https://github.com/submariner-io/lighthouse/issues/286

Configure custom domains

---

Makefile
cmd/manager/main.go
deploy/cluster_role.yaml
pkg/broker/ensure.go
pkg/controller/submariner/submariner_controller.go
pkg/controller/submariner/submariner_controller_test.go
pkg/engine/crds.go
pkg/lighthouse/crds.go
pkg/subctl/operator/lighthouse/crds/ensure.go
pkg/subctl/operator/lighthouse/ensure.go
pkg/subctl/operator/submarinercr/ensure.go
pkg/subctl/operator/submarinerop/crds/ensure.go
pkg/utils/crds/crdutils.go
pkg/utils/createorupdate.go
pkg/utils/createorupdate_test.go

Instead of relying on subctl, Helm charts or OLM to install CRDs other
than the Submariner CRD, take care of everything in the operator.

Install the CRDs in the operator

---

pkg/controller/submariner/submariner_controller.go
scripts/kind-e2e/lib_operator_verify_subm.sh

The route-agent and submariner-gateway pods are now configured
as infrastructure pods which will ignore any existing taints.
Without this route-agent does not run on nodes reserved to
specific workloads via node taints, precluding such workloads
to talk to remote clusters.
This patch also allows reserving nodes just for the submariner
gateway with a submariner taint, and the submariner-gateway
will run in such nodes as long as the submariner.io/gateway
label is set.
Fixes-Issue: https://github.com/submariner-io/submariner/issues/828
Related-Issue: https://github.com/submariner-io/submariner-operator/issues/147

Tolerate Taints in Nodes

---

go.mod
go.sum

Tainted nodes are used for reserving nodes specifically for
workloads. In this case we are supporing the case where
the Gateway node is tainted just for submariner,
and we need the e2e framework pods to run in those nodes.
Related-Issue: #147

Fix subctl verify/benchmark with tainted nodes

---

pkg/subctl/cmd/root.go

If the target cluster has a single candidate node for labeling,
automatically select it instead of asking the user.

Auto-label single-node candidates

---

Makefile

To create a more unified Submariner UX, in the process of standardizing
all repos on "build" target for building all binaries and "images"
target for building all images.

Add images make target to simplify UX

---

pkg/subctl/cmd/benchmark.go

Also tweaked some of the help messages.

Remove "-baseline" term from "intra-cluster" benchmark flag

---

.yamllint.yml

Generated CRDs have changed without corresponding updates to the rules
that ignore them. In CI, yamllint is run in a clean environment without
these generated files and therefore passes, but it will fail locally if
the files exist from other build targets.

Update YAMLLint ignore rules

---

pkg/controller/submariner/submariner_controller.go

Recently a change was made [*] which allows reserving nodes for
submariner gateway with a taint such that Submariner pods can be
scheduled on that nodes. However, the corresponding toleration
was missed for Globalnet pod. This PR fixes it.
[*] https://github.com/submariner-io/submariner-operator/pull/710
Fixes-Issue: https://github.com/submariner-io/submariner/issues/866
Related-Issue: https://github.com/submariner-io/submariner-operator/issues/147

Tolerate Submariner taints in Globalnet Pods

---

pkg/subctl/cmd/show.go

Ignore empty KUBECONFIG entries in subctl show cmds

---

pkg/controller/helpers/helpers.go

If we don't set the controller in the reconciliation loop, we end up
with un-owned resources which aren't deleted when the corresponding
Submariner object is deleted.
Fixes: #749

Ensure the Operator controls the DaemonSets

---

pkg/controller/helpers/helpers.go

Helpers for ConfigMap, Deployment and Service need to set the
ownership when handling conflicts. This ensures that the updated
objects are correctly owned and garbage-collected when the owning
object is deleted.
The DaemonSet helper is handled in #752.
Fixes: #753

Ensure that helpers set ownership correctly

---

.github/workflows/e2e.yml

It seems these git fetches are not necessary.

Remove unnecessary git fetching

---

pkg/subctl/cmd/join.go

kubeconfigs don't always give cluster names, so we mustn't assume that
they do. If they don't, fall back to asking the user as before.
Fixes: #770

Avoid crashing on missing cluster names

---

pkg/broker/rbac.go

The Lighthouse agents needs to access ServiceImports on the broker.

Add broker roles to access multicluster.x-k8s.io

---

pkg/controller/submariner/submariner_controller.go

In an OCP Cluster, openshift-monitoring namespace has couple of
services and these are controlled by their respective operators.
When Globalnet is deployed on OCP, it was seen that globalip
annotation added to such services are periodically getting
deleted by the operators, so Globalnet tries to re-add the
annotation and this goes on forever. This will cause Globalnet
to consume CPU unnecessarily and could affect user-experience
with Submariner Globalnet. We have plans to enhance Globalnet
to improve its scalability, but until then we can exclude
annotating services in openshift-monitoring namespace.

Exclude openshift-monitoring namespace in Globalnet

---

Makefile

```bash
pi@rpi4:~ $ ./subctl-v0.7.0-17-g4719f69-dev-linux-arm deploy-broker --kubeconfig ./k3s.yaml
✓ Deploying broker
✓ Creating broker-info.subm file
✓ A new IPsec PSK will be generated for broker-info.subm
```

Add subctl cross-compiling for arm32 (rpi raspbian)

---

.github/ISSUE_TEMPLATE/flaky_failure_automated.md
.github/workflows/flake_finder.yml

Because this runs against code that has already passed CI to be merged
to the main branch, any failures are likely to be sporadic flakes.
The frequency of this job should be turned up or down depending on how
actively we're hunting for flaky failures

Add periodic E2E tests to find flaky failures

---

Makefile
config/crd/bases/submariner.io_servicediscoveries.yaml
config/crd/bases/submariner.io_submariners.yaml
config/crd/patches/cainjection_in_servicediscoveries.yaml
config/crd/patches/cainjection_in_submariners.yaml
config/crd/patches/webhook_in_servicediscoveries.yaml
config/crd/patches/webhook_in_submariners.yaml
controllers/submariner/submariner_controller_test.go
deploy/mcsapi/crds/multicluster.x_k8s.io_serviceexports.yaml
deploy/mcsapi/crds/multicluster.x_k8s.io_serviceimports.yaml
pkg/engine/crds.go
pkg/subctl/operator/submarinerop/crds/ensure.go
pkg/utils/crds/crdutils.go
pkg/utils/createorupdate.go
pkg/utils/createorupdate_test.go

Use `controller-gen` to generate the CRDs in v1.

build: migrate the CRDs to v1

---

README.md

As flagged by markdown-link-check linting.

Fix broken link to OpenShift with discovery docs

---

.github/workflows/subctl_bleeding_edge.yml

The process for setting environment variables in GitHub Actions has
changed due to a security issue.
See:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-
set-env-and-add-path-commands/

Fix release job, avoid deprecated set-env

---

controllers/submariner/submariner_controller.go

In an OCP Cluster, openshift-dns namespace has dns-default
service and this is controlled by its operator.
When Globalnet is deployed on OCP, it was seen that globalip
annotation added to it is periodically getting deleted by the
operator, so Globalnet tries to re-add the annotation and this
goes on forever. This will cause Globalnet to consume CPU
unnecessarily and could affect user-experience with Submariner
Globalnet. We have plans to enhance Globalnet to improve its
scalability, but until then we can exclude annotating services
in openshift-dns namespace.

Exclude openshift-dns namespace in Globalnet

---

Makefile
go.mod
go.sum
pkg/lighthouse/crds.go
pkg/subctl/cmd/export.go
pkg/subctl/operator/common/embeddedyamls/generators/yamls2go.go

Currently `subctl export service` creates
`serviceexports.lighthouse.submariner.io`
Change it to create `serviceexports.multicluster.x-k8s.io` instead,
inline with switch to MCS Sig API in Lighthouse.
Fixes #798

subctl: Create MCS SIG ServiceExport

---

go.mod
go.sum

Update Lighthouse to latest version to pick the recent fixes done for
E2E flakiness.

Update LH to pick latest E2E

---

.github/ISSUE_TEMPLATE/flaky_failure_automated.md
.github/workflows/flake_finder.yml

There are currently frequent flaky failures, which are causing this
reporting logic to spam our GH issues. Disable it for now, consider
reverting once flaky failures are rare.

Remove flaky test failure automatic reporting

---

scripts/kind-e2e/lib_operator_verify_subm.sh

This was seen in the upgrade tests,
e.g. https://github.com/submariner-io/submariner-operator/pull/920/checks?check_run_id=1460945808
There can be multiple matching secrets; check all of them, and fail if
none of them match the expected ca.crt.

Allow multiple secrets in e2e

---

scripts/kind-e2e/e2e.sh

e2e attempts to run subctl join a second time on cluster2, to check
that doing so doesn't break the cluster, but it doesn't have all the
information used in the initial deployment and can result in a cluster
deployed differently (e.g. strongSwan v. Libreswan).
This patch removes the test for now; if we re-introduce it, it should
probably be a separate test (but see also the upgrade tests).

Stop running subctl join twice

---

apis/submariner/v1alpha1/zz_generated.deepcopy.go
go.sum

Otherwise all images get built with `-dev` suffix
Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

Fix auto generated stuff

---

controllers/helpers/helpers.go
controllers/submariner/submariner_controller.go

This allows engine metrics to be automatically scraped when using the Prometheus operator.
Fixes: #905

Deploy a ServiceMonitor for the engine

---

Makefile
scripts/kind-e2e/lib_operator_verify_subm.sh

Don't pass cable driver flag, instead use new Shipyard using= flag.
As a side effect, this will change the default cable driver in this repo
from strongswan to libreswan.
Relates-to: submariner-io/shipyard#364

Remove hard-coded override of cable driver flag

---

go.mod
go.sum
pkg/controller-gen/main.go

This should be handy for the d/s ci only.
The idea is to use `go run pkg/controller-gen/main.go` instead.
`make embeddedyamls` is based on `controller-gen` which unfortunately does not
have an RPM or Brew package at the moment and can only be downloaded as part of
the go module `sigs.k8s.io/controller-tools`.
When running the d/s CI there is no access to the internet and the only way to
use this tool is by explicitly adding this package to the project.

Add controller-gen as a pkg

---

scripts/kind-e2e/lib_operator_verify_subm.sh

The verification scripts from when the operator was being developed
aren't able to respond to the using=<cable driver> flag, and so fail
when the cable driver doesn't match their default.

Fix cable driver false test failure

---

pkg/subctl/cmd/join.go

... for consistency with the rules given in
https://github.com/submariner-io/submariner-operator/issues/649

Rename --health-check-enable to --health-check

---

pkg/images/images.go
pkg/names/names.go
pkg/subctl/cmd/join.go
pkg/subctl/cmd/show_versions.go
pkg/subctl/operator/submarinerop/deployment/ensure.go

`subctl join` will not add the repository and version properties to submariners
CR but instead these default values will be set by the operator.
For instance when using a custom operator image
or when running `subctl show versions`.

fix(subctl): avoid pinning the version and repo to submariners cr

---

.github/workflows/linting.yml

CRDs should be updated along with any change which causes them to go
out-of-date, e.g. a version bump on Submariner which results in an
update to the underlying types.

Ensure that CRDs are up-to-date

---

controllers/submariner/netwokplugin_syncer.go
controllers/submariner/submariner_controller.go
controllers/submariner/submariner_networkdiscovery.go
pkg/discovery/network/generic_test.go
pkg/discovery/network/network.go
pkg/discovery/network/network_suite_test.go
pkg/discovery/network/ovnkubernetes.go
pkg/discovery/network/ovnkubernetes_test.go

When running in kind, and possibly other clusters OVNKubernetes
works standalone and we need to find the details in the system,
so we can pass them down to the other services.
Fixes-Issue: #999

Detect OVNKubernetes without Cluster Network Operator

---

.github/workflows/flake_finder.yml
.github/workflows/upgrade-e2e.yml

Per discussions on the Automation Sync yesterday, run upgrade tests
periodically against the main branch to find and highlight any
instability. Run in the Flake Finder GHA workflow to better track
results, make spotting unexpected failures easier.

Add upgrade tests to flake finder

---

Makefile

Make sure to rebuild `pkg/subctl/operator/common/embeddedyamls/yamls.go` when one of the RBAC manifests `config/rbac` are changed

fix(makefile): update embedded-yamls when rbac files change

---

controllers/helpers/helpers.go
controllers/servicediscovery/servicediscovery_controller.go
controllers/submariner/submariner_controller.go

The `ImagePullPolicy` will be set to the correct value according to the image tag
in case of using `ImageOverride` flag.

fix: update image pull policy when using image override

---

apis/submariner/v1alpha1/zz_generated.deepcopy.go
pkg/subctl/cmd/benchmark.go
pkg/subctl/cmd/deploybroker.go
pkg/subctl/cmd/export.go
pkg/subctl/cmd/join.go
pkg/subctl/cmd/verify.go

The help library we use produces default help texts where help for
commands starts with an uppercase letter, but help for options starts
with a lowercase letter:
$ subctl help
[...]
help                Help about any command
[...]
-h, --help   help for subctl
[...]
This patch fixes all our help texts to follow the same convention. 
While we're at it, reword a few options for succinctness, and drop
leading "the".

Apply consistent casing to help texts

---

pkg/lighthouse/crds.go
pkg/utils/crds/crdutils.go

On startup, the controller will delete obsolete CRDs (Lighthouse
ServiceImport, ServiceExport, MultiClusterServices), if any are
present.

Delete obsolete CRDs

---

pkg/subctl/cmd/join.go

... to `globalnet` to make it clear that it implies enable/disable.
RE: @renan-campos https://github.com/submariner-io/submariner-operator/pull/972#

Rename flag to skip GlobalNet configuration on join

---

config/rbac/globalnet_cluster_role.yaml

Globalnet controller needs to track serviceexport creation/deletion
so it only allocates GlobalIp for services that are exported.
Refer: https://github.com/submariner-io/submariner/issues/720

Allow globalnet access to serviceexports

---

Makefile

Make sure to set the `DefaultSubmarinerOperatorVersion` during the binary build
Closes #563

fix(subctl): default devel operator image when using subctl:devel

---

controllers/metrics/metrics.go
controllers/servicediscovery/servicediscovery_controller.go
controllers/submariner/submariner_controller.go

This shares the metrics setup code and uses it to setup a
ServiceMonitor for the CoreDNS service.
Fixes: submariner-io/lighthouse#276

Configure Lighthouse CoreDNS metrics

---

controllers/submariner/submariner_controller.go

On OpenShift, we’re seeing reconciliation loops with continuous errors
when updating the status. To avoid this (temporarily), only log the
error, and indicate success; the status should end up being updated at
some point...

Log status update errors without failing

---

pkg/subctl/cmd/join.go

Update the version and repository properties in the submariner spec when using image-override.
Closes #1021

fix(subctl): image-override will override the version and repository properties

---

.github/workflows/linting.yml
.github/workflows/release.yml
apis/submariner/v1alpha1/zz_generated.deepcopy.go
bundle/manifests/submariner.clusterserviceversion.yaml
bundle/manifests/submariner.io_submariners.yaml
config/crd/bases/submariner.io_submariners.yaml
config/manifests/bases/submariner.clusterserviceversion.yaml
controllers/helpers/helpers.go
controllers/servicediscovery/servicediscovery_controller.go
controllers/submariner/netwokplugin_syncer.go
controllers/submariner/submariner_controller.go
controllers/submariner/submariner_networkdiscovery.go
go.mod
go.sum
packagemanifests/0.8.0/submariner.io_submariners.yaml
packagemanifests/0.8.0/submariner.v0.8.0.clusterserviceversion.yaml
pkg/discovery/network/generic_test.go
pkg/discovery/network/network.go
pkg/discovery/network/network_suite_test.go
pkg/discovery/network/ovnkubernetes.go
pkg/discovery/network/ovnkubernetes_test.go
pkg/images/images.go
pkg/names/names.go
pkg/subctl/cmd/join.go
pkg/subctl/cmd/show_versions.go
pkg/subctl/operator/submarinerop/deployment/ensure.go

Backports the following PRs to release-0.8:
- Update references to Lighthouse repo (#1009)
- Ensure that CRDs are up-to-date (#1008)
- Detect OVNKubernetes without Cluster Network Operator (#1001)
- Use the PR base branch as reference when linting (#1026)
- AKS: Use coredns-custom configmap for lighthouse (#1054)
- Fix missing data section in coredns-custom (#1056)
- Reconcile ServiceDiscovery before status updates (#1058)
- Update GatewayEngine Pod env with the host nodeName (#1019)
- chore: update bundle broken links (#1014)
- fix: update image pull policy when using image override (#939)
- Add ClusterId to lighthouse-coredns env (#1053)
- Generate the submariners crd again to update the changes for bundle 0.8.0 (#1007)
- Tag released image with branch name (#1025)
- fix(subctl): avoid …

[release-0.8] Backports for 0.8.1
