submariner-io/submariner-operator

- .travis.yml
- Dockerfile.dapper
- cmd/manager/main.go
- go.mod
- go.sum
- pkg/apis/addtoscheme_submariner_v1alpha1.go
- pkg/apis/submariner/v1alpha1/zz_generated.openapi.go
- pkg/controller/add_submariner.go
- pkg/controller/submariner/submariner_controller.go
- pkg/controller/submariner/submariner_suite_test.go
- scripts/build
- scripts/test
- scripts/validate
Adds a placeholder test suite to make sure ginkgo run on the test
script won't fail.
> Minimal testing and validation on travis

- .travis.yml
- Dockerfile.dapper
- Makefile
- scripts/build
- scripts/e2e
- scripts/kind-e2e/README.md
- scripts/kind-e2e/cluster1-config.yaml
- scripts/kind-e2e/cluster2-config.yaml
- scripts/kind-e2e/cluster3-config.yaml
- scripts/kind-e2e/deploy-operator-local.yaml
- scripts/kind-e2e/e2e.sh
- scripts/kind-e2e/lib_operator_deploy_subm.sh
- scripts/kind-e2e/lib_operator_verify_subm.sh
- scripts/kind-e2e/netshoot.yaml
- scripts/kind-e2e/nginx-demo.yaml
- scripts/kind-e2e/nginx-federated.sh
- scripts/kind-e2e/operator-csv.yaml
- scripts/kind-e2e/operator-group.yaml
- scripts/kind-e2e/operator-source.yaml
- scripts/kind-e2e/operator-subscription.yaml
This copies and adapts the e2e scripts from the main Submariner
project. The ultimate goal is to share all this somehow but for now it
would be nice to have the safety net for the operator.
> Add e2e tests

- go.mod
- go.sum
- pkg/subctl/cmd/create.go
- pkg/subctl/cmd/createbroker.go
- pkg/subctl/cmd/root.go
- pkg/subctl/main.go
- scripts/build-subctl
> Add subctl skeleton

- pkg/broker/crds.go
- pkg/broker/rbac.go
- pkg/subctl/cmd/createbroker.go
- pkg/subctl/cmd/join.go
- pkg/subctl/cmd/joincluster.go
- scripts/build
- scripts/build-operator
- scripts/kind-e2e/e2e.sh
It took me way too long to figure out that we need a different clientset for CRDs...
Depends: #13
> Set the broker up using subctl

- pkg/controller/submariner/submariner_controller.go
- scripts/kind-e2e/lib_operator_deploy_subm.sh
- scripts/kind-e2e/lib_operator_verify_subm.sh
Setting defaults should update the CR; this patch changes the provided
instance and updates the CR.
> Ensure we update the CR after setting defaults

- pkg/broker/ensure.go
- pkg/subctl/cmd/createbroker.go
Pull the broker install logic to it's own package, so the command is cleaner, and add the logic to install the operator along with the broker (which we may make optional)
> Install operator with broker and pull broker creation to it's own module

- pkg/broker/ipsec_psk.go
- pkg/broker/rbac.go
- pkg/subctl/datafile/datafile.go
- pkg/subctl/datafile/datafile_test.go
The method NewFromCluster returns a SubctlData structure from the
cluster, by embedding the API data, broker service account credentials
and IPSEC Key.
> Implements method to get SubctlData from cluster

- .gitignore
> Add gitignore covering all generated files

- pkg/broker/ensure.go
When the broker account is created, the credentials token is created by kubernetes
asynchronously. Without this patch it will fail sometimes because the token isn't created fast enough.
> Wait for the client token to be ready

- pkg/subctl/cmd/join.go
If the user hasn’t provided a cluster id or color codes on the command
line, ask for them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/submariner-io/submariner-operator/54)
> Ask for missing information

- pkg/controller/submariner/submariner_controller.go
- pkg/discovery/network/network.go
- pkg/subctl/cmd/info.go
- pkg/subctl/cmd/root.go
- pkg/subctl/operator/deploy/ensure.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/submariner-io/submariner-operator/60)
> A few patches for the 0.0.3 release to kubecon

- scripts/build-cross
- scripts/build-subctl
Fixes: #64
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/submariner-io/submariner-operator/65)
> Cross-build subctl for Linux/x86, Windows, macOS

- pkg/subctl/cmd/join.go
Depends: #57
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/submariner-io/submariner-operator/59)
> Add debug replica options

- pkg/subctl/cmd/root.go
Closes: #58
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/submariner-io/submariner-operator/92)
> Exclude master nodes from the list to label

- scripts/build-subctl
> Disable upx compression for OSX

- go.mod
- go.sum
- pkg/internal/cli/logger.go
- pkg/internal/cli/spinner.go
- pkg/internal/cli/status.go
- pkg/internal/env/term.go
- pkg/internal/env/term_test.go
- pkg/subctl/cmd/deploybroker.go
- pkg/subctl/cmd/join.go
- pkg/subctl/operator/install/ensure.go
These commits shouldn’t be squashed on merge (I’d like to keep the “import” commit standalone, so that our changes can be more easily rebased if necessary).
> KIND spinners

- pkg/subctl/cmd/join.go
> Avoid crash when no network discovery info

- Dockerfile.dapper
- pkg/subctl/cmd/deploybroker.go
- pkg/subctl/cmd/join.go
- scripts/kind-e2e/e2e.sh
adds kubefed join functionality to subctl
> kubefed join

- pkg/controller/submariner/submariner_controller_test.go
Added more tests for the route agent and error cases.
> Enhance ReconcileSubmariner unit tests

- pkg/subctl/cmd/join.go
- pkg/subctl/lighthouse/dns/ensure.go
> Set the DNS operator up for Lighthouse

- deploy/lighthouse/controller.yaml
- pkg/subctl/lighthouse/deploy/ensure.go
> Pull Lighthouse 0.1.0

- pkg/subctl/cmd/deploybroker.go
- pkg/subctl/lighthouse/deploy/ensure.go
The flags were moved in 15f6dba2ce60 but some checks still use the old
ones, which means that while we do check if kubefedctl is available
when --service-discovery is specified, we then go on to *not* deploy
Lighthouse...
Fixes: #179
> Handle service discovery flags consistently

- .travis.yml
(cherry picked from commit 0ed53324fa83a5c886b26a8096b35d3216e745d2)
> Make travis also build release branches

- pkg/subctl/cmd/join.go
fix https://github.com/submariner-io/submariner-operator/issues/220
> add TrimSpace to input CIDRs

- pkg/discovery/network/network.go
- pkg/subctl/cmd/join.go
- pkg/subctl/cmd/root.go
- pkg/subctl/lighthouse/deploy/ensure.go
This picks a number of fixes from the master branch to the 0.1 release branch. *Do not squash these.*
> Cherry pick release fixes

- pkg/subctl/cmd/join.go
When subctl determines that the OpenShift CVO needs to be disabled, it
asks for confirmation; this patch allows skipping this check (and
forcing the CVO to be disabled, if necessary) with --disable-cvo.
Fixes: #235
> Add flag to disable the OpenShift CVO

- pkg/subctl/lighthouse/dns/ensure.go
This uses the standard K8s retry pattern. It’s not the only place in
subctl where we need to do this, I’ll follow up with another PR to fix
the rest.
Fixes: #236
> Retry dns-operator updates on conflicts

- .travis.yml
- scripts/kind-e2e/e2e.sh
We’re breaking Lighthouse too often, this enables Lighthouse
deployment testing on all PRs.
> Test Lighthouse in Travis

- README.md
(cherry picked from commit cf580e17a57b64fb96ba00020072d2f1fd1d89af)
> Added info about using merged-kubeconfig for joining the cluster.

- pkg/subctl/cmd/deploybroker.go
- scripts/kind-e2e/e2e.sh
> Rename “globalnet-enable” to “globalnet”

- scripts/kind-e2e/e2e.sh
- scripts/kind-e2e/lib_operator_verify_subm.sh
Migrate deployment logic to be based on shipyard.
> E2E deploy with shipyard

- pkg/broker/ensure.go
- pkg/broker/rbac.go
- pkg/subctl/cmd/join.go
- pkg/subctl/datafile/datafile.go
- pkg/subctl/datafile/datafile_test.go
- scripts/kind-e2e/lib_operator_verify_subm.sh
Create a new SA/Role/role binding for each cluster
that is joined to the broker.
Solves issue: #100
Signed-By: Janki Chhatbar <jchhatba@redhat.com>
> Create new SA token for each cluster joined

- pkg/subctl/operator/submarinerop/crds/ensure.go
This will be used to store and report the cluster-local engine
status.
> Add Gateway CRD

- Makefile
- Makefile.dapper
> Use the shared shipyard build infrastructure

- scripts/kind-e2e/e2e.sh
- scripts/kind-e2e/lib_operator_verify_subm.sh
Migrate more parts of the script to use shipyard's capabilities to run kubectl commands in parallel/sequential.
Some misc cleanups were made as part of the process.
> Migrate more parts to shipyard's capabilities

- scripts/kind-e2e/e2e.sh
Pipefail is already globally set on travis, no need to play with it
since turning it off at the end causes e2e failure to be missed.
Also makes sense to set it at the beginning of the script to make sure
the entire experience is consistent wvwn without the CI.
> Don't play with pipefail

- pkg/controller/servicediscovery/servicediscovery_controller.go
> Fixed deployment issues in Openshift

- go.mod
- go.sum
Co-Authored-By: Janki Chhatbar <jchhatba@redhat.com>
> Update submariner and shipyard references

- README.md
> Remove install steps and link to website 

- .travis.yml
Since it was changed to a boolean flag, no need to send true/false
> Globalnet flag adjustment

- .github/workflows/e2e.yaml
- .github/workflows/validations.yaml
Adding a workflow to run the E2E tests in GitHub Actions.
Closes #357
> Add GitHub Actions E2E tests

- .github/workflows/e2e.yaml
- .github/workflows/subctl_bin.yml
See: https://github.com/submariner-io/submariner-operator/pull/370/checks?check_run_id=655958357#step:4:1123
> Fetch whole depth, fixes E2E GH actions (GIT_REF failure)

- pkg/discovery/globalnet/globalnet.go
- pkg/discovery/globalnet/globalnet_test.go
- pkg/subctl/cmd/join.go
Move non-join related functions out of join.go
Signed-ff-by: Janki Chhatbar <jchhatba@redhat.com>
> Refactor join.go

- pkg/discovery/globalnet/globalnet.go
- pkg/internal/cli/status.go
- pkg/subctl/cmd/deploybroker.go
- pkg/subctl/cmd/join.go
- pkg/subctl/operator/submarinercr/ensure.go
Replace Printf usage with status Queues in subctl
Signed-off-by: Janki Chhatbar <jchhatba@redhat.com>
Colour code for WARNING:
> Move away from Printf

- scripts/kind-e2e/e2e.sh
Some cleanups of the e2e.sh script
> E2e cleanup

- Dockerfile.dapper
Regarding issue #563 - remove old reference to kubefed
> Remove dangling KubeFed references

- .github/workflows/subctl_bleeding_edge.yml
- scripts/build-subctl
Fix the quotes which broken the job, also the script should build the
tar.xz into bin directory.
> Fix bleeding edge release

- .github/workflows/subctl_bleeding_edge.yml
- README.md
- scripts/build-subctl
Also updated README to point to the stable, and the devel release.
Resolves #425 
Depends on (and includes) #428
> Use devel tag for bleeding edge release

- pkg/subctl/cmd/join.go
Lighthouse does not disable CVO with updated implementation,
hence removed the warning.
> Remove CVO disable warning

- pkg/controller/servicediscovery/servicediscovery_controller.go
The update configmap was adding forward plugin entires,
without checking if an entry exisits. A check has been
added to skip if the entry exists already.
> Fix duplicate forward plugin entries

- pkg/subctl/cmd/verify.go
The help message referred to incorrect flags. Also expanded/improved the help
and prompt messages.
> Update subctl verify messages

- pkg/subctl/datafile/datafile.go
Currently, calls to GetBrokerAdministratorConfig return a config which
has been verified in some cases, but not in others. This patch ensures
the config is verified in all cases and refactors the code to match
the Submariner implementation.
> Check the retrieved clientset in all cases

- pkg/controller/servicediscovery/servicediscovery_controller.go
The forward plugin entry will be updated if the Lighthouse
DNS service IP changes.
> Update forward plugin Server IP

- deploy/crds/submariner.io_submariners_crd.yaml
- pkg/apis/submariner/v1alpha1/zz_generated.openapi.go
It seems we never re-generated the operator with the list of gateways;
this fixes that.
> Add gatewayList information to the CRD

- CODEOWNERS
Related-Issue: https://github.com/submariner-io/submariner/issues/662
> Add skitt to submariner-operator CODEOWNERS

- .github/workflows/release.yaml
Without this fix git describe will fail, and release will stop.
Signed-off-by: Miguel Angel Ajo Pelayo <majopela@redhat.com>
> Fix release E2E

- scripts/kind-e2e/cluster_settings
- scripts/kind-e2e/e2e.sh
We don't really need 3 clusters, use only 2 for testing the operator
works.
> Use only two clusters for E2E

- deploy/crds/submariner.io_servicediscoveries_crd.yaml
- pkg/apis/submariner/v1alpha1/servicediscovery_types.go
- pkg/apis/submariner/v1alpha1/zz_generated.openapi.go
- pkg/controller/submariner/submariner_controller.go
> Add globalnet flag for lighthouse

- .github/workflows/subctl_bleeding_edge.yml
- Makefile
* Use Cutting Edge instead of bleeding edge
* Update to dist directory (as par recent changes in the Makefile)
* Rename -vx.x.x(-x-xxxxx) to -devel in the package filename
Co-Authored-By: Mike Kolesnik <mkolesni@redhat.com>
> Update the devel release handling of subctl

- pkg/controller/submariner/submariner_controller.go
Since we reconcile Submariner instances, we need to cause Gateway
changes to result in a Submariner reconciliation (which will then
retrieve all the Gateway instances in the namespace).
Fixes: #533
> Enqueue Submariner reconciliation when Gateway changes

- pkg/subctl/cmd/export.go
- pkg/subctl/cmd/root.go
> subctl: add export service

- Makefile
- pkg/controller/submariner/submariner_controller.go
- pkg/images/images.go
- pkg/subctl/cmd/join.go
- pkg/subctl/cmd/root.go
> Remove --operator-image parameter

- pkg/versions/versions.go
> Update operator version to v0.5.0-pre0

- pkg/versions/versions.go
> Update operator version to v0.5.0-pre1

- deploy/submariner/globalnet_cluster_role.yaml
> Add ClusterRole for Globalnet to query ServiceExport object

- .golangci.yml
- pkg/broker/rbac.go
On top of https://github.com/submariner-io/submariner-operator/pull/573.
> Enable gofmt linter, fix errors

- .golangci.yml
- pkg/controller/submariner/submariner_controller.go
On top of https://github.com/submariner-io/submariner-operator/pull/573.
> Add misspell linter, fix errors

- pkg/subctl/cmd/verify.go
Read the operator Submariner resource from one of the clusters and
check the GlobalCIDR field.
> Detect globalnet in subctl verify

- pkg/subctl/cmd/show_connections.go
> Add subctl show connections cmd

- pkg/subctl/cmd/show_endpoints.go
> Add subctl show endpoints cmd

- pkg/subctl/cmd/show_gateways.go
> Add subctl cmd show gateways

- pkg/subctl/cmd/show_all.go
> Add subctl cmd show all

- pkg/subctl/cmd/show_gateways.go
> Fix subctl show gateways: correct the Summary msg

- go.mod
- go.sum
To unbreak the e2e tests since the test code has changed.
Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>
> Bump lighthouse

- .golangci.yml
- pkg/controller/submariner/submariner_networkdiscovery.go
- pkg/subctl/operator/lighthouse/serviceaccount/ensure.go
- pkg/subctl/operator/submarinerop/serviceaccount/ensure.go
Builds on https://github.com/submariner-io/submariner-operator/pull/581
> Enable unparam unused param linting, fix errors

- deploy/lighthouse/cluster_role.yaml
- pkg/broker/rbac.go
* ClusterRoles for broker and Lighthouse ServiceAccounts
to access endpoing slices
* ClusterRole for Lighthouse ServiceAccout to access Endpoint
> Add ClusterRole for endpoint slice

- .golangci.yml
- cmd/manager/main.go
- pkg/broker/ensure.go
- pkg/controller/servicediscovery/servicediscovery_controller.go
- pkg/controller/submariner/submariner_controller.go
- pkg/controller/submariner/submariner_controller_test.go
- pkg/discovery/network/network.go
- pkg/subctl/cmd/export.go
- pkg/subctl/cmd/show_versions.go
- pkg/subctl/operator/submarinercr/ensure.go
> Enable lll line length linting, fix errors

- pkg/subctl/cmd/export.go
> Add serviceName to subctl export service help

- pkg/subctl/cmd/show_connections.go
- pkg/subctl/cmd/show_endpoints.go
- pkg/subctl/cmd/show_gateways.go
Fix issue https://github.com/submariner-io/enhancements/issues/5
> Print 'no resource found' in show cmds

- pkg/subctl/cmd/show_connections.go
- pkg/subctl/cmd/show_endpoints.go
> Increase field size in subctl show connections and show endpoints cmds

- pkg/controller/servicediscovery/servicediscovery_controller.go
MCS API now uses `clusterset.local` instead of `supercluster.local` as
zone for multicluster service discovery. To support any existing
deployments, support `supercluster` for at least one release to allow
users to switch to `clusterset`
> Retain supercluster in dns configmap

- .golangci.yml
- pkg/subctl/datafile/datafile.go
- pkg/subctl/datafile/datafile_test.go
> Enable gosec linting, fix errors

- pkg/subctl/cmd/show_gateways.go
> Increase field size in show gateways cmd

- pkg/subctl/cmd/show_versions.go
> Enable show version to work for multiple kubeconfig files

- pkg/subctl/cmd/root.go
- pkg/subctl/cmd/show.go
- pkg/subctl/cmd/show_all.go
- pkg/subctl/cmd/show_connections.go
- pkg/subctl/cmd/show_endpoints.go
- pkg/subctl/cmd/show_gateways.go
- pkg/subctl/cmd/show_networks.go
- pkg/subctl/cmd/show_versions.go
> Use cluster name instead of context in subctl show cmds

- pkg/subctl/cmd/show_connections.go
- pkg/subctl/cmd/show_endpoints.go
- pkg/subctl/cmd/show_versions.go
> Align fields in subctl show cmds

- pkg/subctl/operator/submarinercr/ensure.go
When joining a cluster, we currently try to update existing Submariner
CRs. But this causes problems if the CRD has been updated in a
non-backwards-compatible fashion (which is allowable since it's still
v1alpha1): on conflict, we try to retrieve the current CR, but that
fails because the existing CR doesn't match the CRD and therefore
can't be unmarshalled. The only reason we retrieve the existing CR is
to copy its resource version to the new CR.
With this change, existing CRs are blindly deleted on conflict, which
allows upgrades to proceed.
> Delete existing CRs when joining

- pkg/subctl/benchmark/throughput.go
> Better handling for cleanups for the throughput tests

- pkg/controller/servicediscovery/servicediscovery_controller.go
- pkg/controller/servicediscovery/servicediscovery_controller_test.go
If custom domains are configured update the Coredns and lighthouse dns
configmaps with relevant configuration.
> Update configmap with custom domains

- .github/stale.yml
Signed-off-by: nyechiel <n.yechiel@gmail.com>
> Add stalebot to operator repo

- go.mod
- go.sum
- pkg/subctl/benchmark/latency.go
- pkg/subctl/cmd/benchmark.go
- pkg/subctl/cmd/verify.go
> Add intra-cluster test to subctl latency benchmark

- cmd/manager/main.go
Instead of crashing and then restarting, or requiring the deployment
to create the ServiceDiscovery CRD, restart the operator after
creating or updating the Lighthouse CRDs.
Thanks to Miguel Angel Ajo Pelayo for the suggestion!
Fixes: #733
> Restart the operator if we update Lighthouse CRDs

- go.mod
- go.sum
> Update Lighthouse Version

- .github/workflows/codeowners.yml
- CODEOWNERS
- CODEOWNERS.in
See commit messages for details.
> Generate CODEOWNERS, add CI

- pkg/apis/submariner/v1alpha1/submariner_types.go
- pkg/controller/submariner/submariner_controller.go
- pkg/controller/submariner/submariner_controller_test.go
- pkg/controller/submariner/submariner_networkdiscovery.go
> Pass network plugin to route-agent pod

- go.mod
- go.sum
> Fix Lighthouse e2e failures

- .github/ISSUE_TEMPLATE/flaky_failure_automated.md
- .github/workflows/flake_finder.yml
The previous GHA failed with an unclear error. Use a different GHA.
> Fix GH issue reporting on flaky test failures

- go.mod
- go.sum
Pick latest code from lighthouse with fixes for flaky e2e
> Use latest E2E from lighthouse

- pkg/subctl/operator/common/serviceaccount/ensure.go
- pkg/subctl/operator/lighthouse/serviceaccount/ensure.go
- pkg/subctl/operator/submarinerop/serviceaccount/ensure.go
Refactored the `submarinerop` and `lighthouse` service account code and extracted reusable functions into the `common` package.
> Refactor and deduplicate service account code

- deploy/mcsapi/crds/multicluster.x_k8s.io_serviceexports.yaml
- deploy/mcsapi/crds/multicluster.x_k8s.io_serviceimports.yaml
Update the MCS API CRDs as per definition in
https://github.com/kubernetes-sigs/mcs-api/tree/master/config/crd
> Fix MCS API CRDs

- go.mod
- go.sum
LH e2e has been modified to use MCS SIG APIs
> Update LH e2e to latest

- pkg/subctl/cmd/join.go
To override one or multiple component images we can use the flag
`--image-override=<component1>=<image_path1>,<component2>=<image_path2>,...`
or
`--image-override=<component1>=<image_path1> --image-override=<component2>=<image_path2> --image-override=...`
as part of `subctl join`.
```
subctl join broker-info.subm --kubeconfig output/kubeconfigs/kind-config-cluster1 --clusterid cluster1 --cable-driver libreswan --disable-nat --version devel --image-override=submariner-route-agent=quay.io/smattar/submariner-route-agent:v0.4-2,submariner=quay.io/smattar/submariner:v0.4-2
subctl join broker-info.subm --kubeconfig output/kubeconfigs/kind-config-cluster2 --clusterid cluster2 --cable-driver libreswan --disable-nat --version devel --image-override=submariner-route-agent=quay.io/smattar/submariner- …
```
> feat: add image-override flag to subctl command

- apis/submariner/v1alpha1/zz_generated.deepcopy.go
- controllers/submariner/netwokplugin_syncer.go
- controllers/submariner/submariner_controller.go
- pkg/names/names.go
> Setup a networkplugin-syncer deployment for OVNKubernetes

- controllers/servicediscovery/servicediscovery_controller.go
> Fix logging in servicediscovery controller

- bundle/manifests/submariner.io_submariners.yaml
- config/crd/bases/submariner.io_submariners.yaml
- packagemanifests/0.8.0/submariner.io_submariners.yaml
> Generate the submariners crd again to update the changes for bundle 0.8.0

- go.mod
- go.sum
Updating the reference to get the following fix from LH repo
https://github.com/submariner-io/lighthouse/pull/424
> Update references to Lighthouse repo

- controllers/submariner/submariner_controller.go
Related to: https://github.com/submariner-io/submariner/issues/970
> Update Globalnet Pod env with the host nodeName

- controllers/submariner/submariner_controller.go
Related to: https://github.com/submariner-io/submariner/issues/1068
> Update GatewayEngine Pod env with the host nodeName

- README.md
> chore: remove broken link in readme.md

- .github/workflows/flake_finder.yml
> Stop testing strongSwan

- controllers/servicediscovery/servicediscovery_controller.go
Lighthouse makes changes to `coredns` configmap to forward
`clusterset.local` queries to lighthouse coredns server. But
AKS doesn't allow changes to this configmap by overwriting any
changes.
AKS provides `custom-coredns` for such changes, so lighthouse
should use that.
Fixes #1046
> AKS: Use coredns-custom configmap for lighthouse

- controllers/servicediscovery/servicediscovery_controller.go
> Fix missing data section in coredns-custom

- .github/workflows/e2e.yml
- Makefile
- scripts/kind-e2e/cluster_settings.ovn
> Enable OVN CNI
